### ISSUE TITLE
全都翻译完了？

### ISSUE THREAD

**Issue by riku** [gotgit/git-l10n-zh-cn#11]
为什么有些地方还是显示英文？是不是因为没有进入 po 文件？

比如 git help 

git status
fatal: Not a git repository (or any of the parent directories): .git

**Comment by jiangxin** [comment]
Git i18n 还在完善中，你发现的问题可以写个补丁发到官方列表。具体方法参见： https://github.com/git/git/blob/master/Documentation/SubmittingPatches 。

**Comment by riku** [comment]
好的。

2012/2/2 Jiang Xin <
reply@reply.github.com
