### ISSUE TITLE
确认 rebase 的翻译

### ISSUE THREAD

**Issue by riku** [gotgit/git-l10n-zh-cn#2]
rebase 应该怎么翻译？“变基”还是“衍合”？

**Comment by jiangxin** [comment]
我觉得变基好。 re=改变，base=基础。还有repository用版本库比仓库好，搜索引擎的条目量也是依据之一。

**Comment by jiangxin** [comment]
没有关系先翻完，之后统一替换。

**Comment by riku** [comment]
好的。

2012/2/1 Jiang Xin <
reply@reply.github.com
