### ISSUE TITLE
will become dangling 如何翻译？

### ISSUE THREAD

**Issue by riku** [gotgit/git-l10n-zh-cn#7]

**Comment by jiangxin** [comment]
dangling 这里翻成“孤零”不知可否。

**Comment by riku** [comment]
我也不能确定，要不先这么翻译吧。

On Wed, Feb 1, 2012 at 2:05 PM, Jiang Xin <
reply@reply.github.com

**Comment by jiangxin** [comment]
翻成悬空了。

**Comment by riku** [comment]
好的
在 2012-2-1 下午5:50，"Jiang Xin" <
reply@reply.github.com
